import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
   title: "LIGHT STUDIO",
   description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <Layout>
               <Header />
               {children}
               <Footer />
            </Layout>
         </body>
      </html>
   );
}
